<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 15:33:37                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoIngIngredientDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'ing_ingredient';
		}
		
		public function getObjectName()
		{
			return 'IngIngredient';
		}
		
		public function getSequence()
		{
			return 'ing_ingredient_id';
		}
		
		public function getLinkName()
		{
			return 'ing';
		}
	}
?>