<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 20:26:37                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoIngLogDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'ing_log';
		}
		
		public function getObjectName()
		{
			return 'IngLog';
		}
		
		public function getSequence()
		{
			return 'ing_log_id';
		}
		
		public function getLinkName()
		{
			return 'ing';
		}
	}
?>