<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 14:43:52                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class IngAdminDAO extends AutoIngAdminDAO implements ILoginUserDigestDAO
	{	
		/**
		 * @param string $email
		 * @return IngAdmin
		 */
		public function findByAuthParam($email) {
			return Criteria::create($this)
				->add(Expression::eq(
					SQLFunction::create('lower', 'email'),
					DBValue::create(mb_strtolower($email))
				))
				->setLimit(1)
				->get();
		}
	}
?>