<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 14:43:52                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class IngAdminDAO extends AutoIngAdminDAO
	{
		/**
		 * @return FbUser 
		 */
		public function getByEmailAndPassword($email, $password)
		{
			Assert::isString($email, 'email must not be empty');
			Assert::isString($password, 'password must not be empty');
			$password = md5(IngAdmin::SALT.$password.IngAdmin::SALT);
			
			return Criteria::create($this)->
				add(Expression::eq('email', DBValue::create($email)))->
				add(Expression::eq('password', DBValue::create($password)))->
				setLimit(1)->
				get();
		}
	}
?>