<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2012-03-13 00:10:53                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class IngAdminFavoriteProductsDAO extends ManyToManyLinked
	{
		public function __construct(IngAdmin $ingAdmin, $lazy = false)
		{
			parent::__construct(
				$ingAdmin,
				IngProduct::dao(),
				$lazy
			);
		}
		
		/**
		 * @return IngAdminFavoriteProductsDAO
		**/
		public static function create(IngAdmin $ingAdmin, $lazy = false)
		{
			return new self($ingAdmin, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'ing_admin_ing_product';
		}
		
		public function getChildIdField()
		{
			return 'ing_product_id';
		}
		
		public function getParentIdField()
		{
			return 'ing_admin_id';
		}
	}
?>