<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 20:26:37                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class IngLogDAO extends AutoIngLogDAO
	{
		// your brilliant stuff goes here
	}
?>