<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-16 15:00:51                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class IngReceiptIngredientsDAO extends OneToManyLinked
	{
		public function __construct(IngReceipt $ingReceipt, $lazy = false)
		{
			parent::__construct(
				$ingReceipt,
				IngIngredient::dao(),
				$lazy
			);
		}
		
		/**
		 * @return IngReceiptIngredientsDAO
		**/
		public static function create(IngReceipt $ingReceipt, $lazy = false)
		{
			return new self($ingReceipt, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'receipt_id';
		}
	}
?>