<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-16 14:30:05                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoIngReceipt extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'IngReceipt', 8, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 64, true, true, false, null, null),
				'product' => LightMetaProperty::fill(new LightMetaProperty(), 'product', 'product_id', 'integerIdentifier', 'IngProduct', null, true, false, false, 1, 3),
				'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, null, false, true, false, null, null),
				'ingredients' => LightMetaProperty::fill(new LightMetaProperty(), 'ingredients', 'ingredients_id', 'identifierList', 'IngIngredient', null, false, false, false, 2, null)
			);
		}
	}
?>