<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-16 12:47:14                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoIngIngredient extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'IngIngredient', 8, true, true, false, null, null),
				'product' => LightMetaProperty::fill(new LightMetaProperty(), 'product', 'product_id', 'integerIdentifier', 'IngProduct', null, true, false, false, 1, 3),
				'receipt' => LightMetaProperty::fill(new LightMetaProperty(), 'receipt', 'receipt_id', 'integerIdentifier', 'IngReceipt', null, true, false, false, 1, 3),
				'weight' => LightMetaProperty::fill(new LightMetaProperty(), 'weight', null, 'float', null, 4, false, true, false, null, null),
				'count' => LightMetaProperty::fill(new LightMetaProperty(), 'count', null, 'float', null, 4, false, true, false, null, null),
				'comment' => LightMetaProperty::fill(new LightMetaProperty(), 'comment', null, 'string', null, null, false, true, false, null, null)
			);
		}
	}
?>