<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 20:26:37                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoIngLog extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'IngLog', 8, true, true, false, null, null),
				'message' => LightMetaProperty::fill(new LightMetaProperty(), 'message', null, 'string', null, null, true, true, false, null, null),
				'objectName' => LightMetaProperty::fill(new LightMetaProperty(), 'objectName', 'object_name', 'string', null, 64, false, true, false, null, null),
				'objectId' => LightMetaProperty::fill(new LightMetaProperty(), 'objectId', 'object_id', 'string', null, 64, false, true, false, null, null),
				'adminId' => LightMetaProperty::fill(new LightMetaProperty(), 'adminId', 'admin_id', 'integer', null, 4, true, true, false, null, null),
				'insertDate' => LightMetaProperty::fill(new LightMetaProperty(), 'insertDate', 'insert_date', 'timestamp', 'Timestamp', null, true, true, false, null, null)
			);
		}
	}
?>