<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2012-03-13 00:10:53                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoIngAdmin extends NamedObject implements IPermissionUser, ILoginUserDigest
	{
		protected $email = null;
		protected $passwordHash = null;
		protected $loginKey = null;
		protected $favoriteProducts = null;
		
		public function getEmail()
		{
			return $this->email;
		}
		
		/**
		 * @return IngAdmin
		**/
		public function setEmail($email)
		{
			$this->email = $email;
			
			return $this;
		}
		
		public function getPasswordHash()
		{
			return $this->passwordHash;
		}
		
		/**
		 * @return IngAdmin
		**/
		public function setPasswordHash($passwordHash)
		{
			$this->passwordHash = $passwordHash;
			
			return $this;
		}
		
		public function getLoginKey()
		{
			return $this->loginKey;
		}
		
		/**
		 * @return IngAdmin
		**/
		public function setLoginKey($loginKey)
		{
			$this->loginKey = $loginKey;
			
			return $this;
		}
		
		/**
		 * @return IngAdminFavoriteProductsDAO
		**/
		public function getFavoriteProducts($lazy = false)
		{
			if (!$this->favoriteProducts || ($this->favoriteProducts->isLazy() != $lazy)) {
				$this->favoriteProducts = new IngAdminFavoriteProductsDAO($this, $lazy);
			}
			
			return $this->favoriteProducts;
		}
		
		/**
		 * @return IngAdmin
		**/
		public function fillFavoriteProducts($collection, $lazy = false)
		{
			$this->favoriteProducts = new IngAdminFavoriteProductsDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->favoriteProducts->mergeList($collection);
			
			return $this;
		}
	}
?>