<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 15:41:15                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoIngProduct extends NamedObject
	{
		protected $description = null;
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return IngProduct
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
	}
?>