<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-16 14:30:05                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoIngReceipt extends NamedObject
	{
		protected $product = null;
		protected $productId = null;
		protected $description = null;
		protected $ingredients = null;
		
		/**
		 * @return IngProduct
		**/
		public function getProduct()
		{
			if (!$this->product && $this->productId) {
				$this->product = IngProduct::dao()->getById($this->productId);
			}
			
			return $this->product;
		}
		
		public function getProductId()
		{
			return $this->productId;
		}
		
		/**
		 * @return IngReceipt
		**/
		public function setProduct(IngProduct $product)
		{
			$this->product = $product;
			$this->productId = $product->getId();
			
			return $this;
		}
		
		/**
		 * @return IngReceipt
		**/
		public function setProductId($id)
		{
			$this->product = null;
			$this->productId = $id;
			
			return $this;
		}
		
		/**
		 * @return IngReceipt
		**/
		public function dropProduct()
		{
			$this->product = null;
			$this->productId = null;
			
			return $this;
		}
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return IngReceipt
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
		
		/**
		 * @return IngReceiptIngredientsDAO
		**/
		public function getIngredients($lazy = false)
		{
			if (!$this->ingredients || ($this->ingredients->isLazy() != $lazy)) {
				$this->ingredients = new IngReceiptIngredientsDAO($this, $lazy);
			}
			
			return $this->ingredients;
		}
		
		/**
		 * @return IngReceipt
		**/
		public function fillIngredients($collection, $lazy = false)
		{
			$this->ingredients = new IngReceiptIngredientsDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->ingredients->mergeList($collection);
			
			return $this;
		}
	}
?>