<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2012-03-11 01:29:28                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoIngAdmin extends NamedObject implements IPermissionUser, ILoginUserDigest
	{
		protected $email = null;
		protected $passwordHash = null;
		protected $loginKey = null;
		
		public function getEmail()
		{
			return $this->email;
		}
		
		/**
		 * @return IngAdmin
		**/
		public function setEmail($email)
		{
			$this->email = $email;
			
			return $this;
		}
		
		public function getPasswordHash()
		{
			return $this->passwordHash;
		}
		
		/**
		 * @return IngAdmin
		**/
		public function setPasswordHash($passwordHash)
		{
			$this->passwordHash = $passwordHash;
			
			return $this;
		}
		
		public function getLoginKey()
		{
			return $this->loginKey;
		}
		
		/**
		 * @return IngAdmin
		**/
		public function setLoginKey($loginKey)
		{
			$this->loginKey = $loginKey;
			
			return $this;
		}
	}
?>