<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 20:26:37                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoIngLog extends IdentifiableObject
	{
		protected $message = null;
		protected $objectName = null;
		protected $objectId = null;
		protected $adminId = null;
		protected $insertDate = null;
		
		public function getMessage()
		{
			return $this->message;
		}
		
		/**
		 * @return IngLog
		**/
		public function setMessage($message)
		{
			$this->message = $message;
			
			return $this;
		}
		
		public function getObjectName()
		{
			return $this->objectName;
		}
		
		/**
		 * @return IngLog
		**/
		public function setObjectName($objectName)
		{
			$this->objectName = $objectName;
			
			return $this;
		}
		
		public function getObjectId()
		{
			return $this->objectId;
		}
		
		/**
		 * @return IngLog
		**/
		public function setObjectId($objectId)
		{
			$this->objectId = $objectId;
			
			return $this;
		}
		
		public function getAdminId()
		{
			return $this->adminId;
		}
		
		/**
		 * @return IngLog
		**/
		public function setAdminId($adminId)
		{
			$this->adminId = $adminId;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getInsertDate()
		{
			return $this->insertDate;
		}
		
		/**
		 * @return IngLog
		**/
		public function setInsertDate(Timestamp $insertDate)
		{
			$this->insertDate = $insertDate;
			
			return $this;
		}
		
		/**
		 * @return IngLog
		**/
		public function dropInsertDate()
		{
			$this->insertDate = null;
			
			return $this;
		}
	}
?>