<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-16 12:47:14                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoIngIngredient extends IdentifiableObject
	{
		protected $product = null;
		protected $productId = null;
		protected $receipt = null;
		protected $receiptId = null;
		protected $weight = null;
		protected $count = null;
		protected $comment = null;
		
		/**
		 * @return IngProduct
		**/
		public function getProduct()
		{
			if (!$this->product && $this->productId) {
				$this->product = IngProduct::dao()->getById($this->productId);
			}
			
			return $this->product;
		}
		
		public function getProductId()
		{
			return $this->productId;
		}
		
		/**
		 * @return IngIngredient
		**/
		public function setProduct(IngProduct $product)
		{
			$this->product = $product;
			$this->productId = $product->getId();
			
			return $this;
		}
		
		/**
		 * @return IngIngredient
		**/
		public function setProductId($id)
		{
			$this->product = null;
			$this->productId = $id;
			
			return $this;
		}
		
		/**
		 * @return IngIngredient
		**/
		public function dropProduct()
		{
			$this->product = null;
			$this->productId = null;
			
			return $this;
		}
		
		/**
		 * @return IngReceipt
		**/
		public function getReceipt()
		{
			if (!$this->receipt && $this->receiptId) {
				$this->receipt = IngReceipt::dao()->getById($this->receiptId);
			}
			
			return $this->receipt;
		}
		
		public function getReceiptId()
		{
			return $this->receiptId;
		}
		
		/**
		 * @return IngIngredient
		**/
		public function setReceipt(IngReceipt $receipt)
		{
			$this->receipt = $receipt;
			$this->receiptId = $receipt->getId();
			
			return $this;
		}
		
		/**
		 * @return IngIngredient
		**/
		public function setReceiptId($id)
		{
			$this->receipt = null;
			$this->receiptId = $id;
			
			return $this;
		}
		
		/**
		 * @return IngIngredient
		**/
		public function dropReceipt()
		{
			$this->receipt = null;
			$this->receiptId = null;
			
			return $this;
		}
		
		public function getWeight()
		{
			return $this->weight;
		}
		
		/**
		 * @return IngIngredient
		**/
		public function setWeight($weight)
		{
			$this->weight = $weight;
			
			return $this;
		}
		
		public function getCount()
		{
			return $this->count;
		}
		
		/**
		 * @return IngIngredient
		**/
		public function setCount($count)
		{
			$this->count = $count;
			
			return $this;
		}
		
		public function getComment()
		{
			return $this->comment;
		}
		
		/**
		 * @return IngIngredient
		**/
		public function setComment($comment)
		{
			$this->comment = $comment;
			
			return $this;
		}
	}
?>