<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 18:35:28                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoIngAdmin extends NamedObject implements IPermissionUser
	{
		protected $email = null;
		protected $password = null;
		
		public function getEmail()
		{
			return $this->email;
		}
		
		/**
		 * @return IngAdmin
		**/
		public function setEmail($email)
		{
			$this->email = $email;
			
			return $this;
		}
		
		public function getPassword()
		{
			return $this->password;
		}
		
		/**
		 * @return IngAdmin
		**/
		public function setPassword($password)
		{
			$this->password = $password;
			
			return $this;
		}
	}
?>