<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 14:43:52                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class IngAdmin extends AutoIngAdmin implements Prototyped, DAOConnected
	{
		const REALM = 'Authorisation required';
		
		public static function getRealm() {
			return self::REALM;
		}
		
		/**
		 * @return IngAdmin
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return IngAdminDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('IngAdminDAO');
		}
		
		/**
		 * @return ProtoIngAdmin
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoIngAdmin');
		}
		
		// your brilliant stuff goes here
		
		/**
		 * Возвращает список действий, доступных пользователю
		 * @return array
		 */
		public function getActionList()
		{
			return array('all');
		}
	}
?>