<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 15:33:37                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class IngIngredient extends AutoIngIngredient implements Prototyped, DAOConnected
	{
		/**
		 * @return IngIngredient
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return IngIngredientDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('IngIngredientDAO');
		}
		
		/**
		 * @return ProtoIngIngredient
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoIngIngredient');
		}
		
		// your brilliant stuff goes here
	}
?>