<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 20:26:37                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class IngLog extends AutoIngLog implements Prototyped, DAOConnected
	{
		/**
		 * @return IngLog
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return IngLogDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('IngLogDAO');
		}
		
		/**
		 * @return ProtoIngLog
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoIngLog');
		}
		
		// your brilliant stuff goes here
		
		/**
		 * Возвращает заполненный лог админки
		 * @param mixed $data
		 * @param IdentifiableObject $object 
		 */
		public static function createByObject($data, IdentifiableObject $object, IngAdmin $admin)
		{
			Assert::isNotNull($object->getId(), 'Object must has id');
			return self::create()->
				setAdminId($admin->getId())->
				setInsertDate(Timestamp::create('now'))->
				setObjectId($object->getId())->
				setObjectName(get_class($object))->
				setMessage(print_r($data, true));
		}
		
		/**
		 * @return IngAdmin
		 */
		public function getAdmin()
		{
			return $this->adminId ? IngAdmin::dao()->getById($this->adminId) : null;
		}
	}
?>