<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-10-15 14:43:52                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class IngProduct extends AutoIngProduct implements Prototyped, DAOConnected
	{
		/**
		 * @return IngProduct
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return IngProductDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('IngProductDAO');
		}
		
		/**
		 * @return ProtoIngProduct
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoIngProduct');
		}
		
		// your brilliant stuff goes here
	}
?>